### ISSUE TITLE
500 Internal Server Error at packagephobia.com (package: sync-request-curl)

### ISSUE THREAD

**Issue by nktnet1** [styfle/packagephobia#1063]
When searching my package:
- https://packagephobia.com/result?p=sync-request-curl

I'm now getting the following error (was okay in the past): 

![sync-request-curl-packagephobia](https://github.com/user-attachments/assets/d79936a5-a3a0-493a-a3e7-20bb33033438)

**Comment by nktnet1** [comment]
I tried running the project locally and it works fine on Node v20.
However, when switching to node v22, it crashes.

The issue is because [node-libcurl](https://github.com/JCMais/node-libcurl), a dependency, fails to install on node v22. Logs here:

<details close>
<summary>Click to view logs</summary>

```
$ npx vercel dev
Vercel CLI 39.2.0
> Ready! Available at http://localhost:3000
NODE_ENV: undefined
isProd:  false
TMPDIR:  /var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/
HOME:  /var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/
AWS_SECRET_ACCESS_KEY:  undefined
(node:22445) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
GET localhost:3000/result?p=node-libcurl
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0
lrucache miss
fetchJSON 127ms
Cache miss - running "npm i node-libcurl@4.0.0" in /var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/...
Unexpected Error Occurred... Error: Command failed: /Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/bin/npm-cli.js i node-libcurl@4.0.0
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated npmlog@5.0.1: This package is no longer supported.
npm WARN deprecated npmlog@7.0.1: This package is no longer supported.
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated are-we-there-yet@4.0.2: This package is no longer supported.
npm WARN deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated gauge@3.0.2: This package is no longer supported.
npm WARN deprecated gauge@5.0.2: This package is no longer supported.
npm ERR! code 1
npm ERR! path /private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
npm ERR! Failed to execute '/Users/khiettamnguyen/.local/share/fnm/node-versions/v22.12.0/installation/bin/node /Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/lib/binding --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
npm ERR! node-pre-gyp info using node@22.12.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v4.0.0/node_libcurl-v4.0.0-node-v127-darwin-arm64-unknown.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/JCMais/node-libcurl/releases/download/v4.0.0/node_libcurl-v4.0.0-node-v127-darwin-arm64-unknown.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for node-libcurl@4.0.0 and node@22.12.0 (node-v127 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/JCMais/node-libcurl/releases/download/v4.0.0/node_libcurl-v4.0.0-node-v127-darwin-arm64-unknown.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@22.12.0 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@22.12.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.12.6 found at "/Users/khiettamnguyen/.pyenv/versions/3.12.6/bin/python3"
npm ERR! gyp info spawn /Users/khiettamnguyen/.pyenv/versions/3.12.6/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args '/Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'make',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/build/config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/Library/Caches/node-gyp/22.12.0/include/node/common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/Library/Caches/node-gyp/22.12.0',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=/Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/Library/Caches/node-gyp/22.12.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@22.12.0 | darwin | arm64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! clang++: error: no such file or directory: '/usr/include'
npm ERR! make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (/Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
npm ERR! gyp ERR! System Darwin 24.0.0
npm ERR! gyp ERR! command "/Users/khiettamnguyen/.local/share/fnm/node-versions/v22.12.0/installation/bin/node" "/Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/lib/binding" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v127"
npm ERR! gyp ERR! cwd /private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl
npm ERR! gyp ERR! node -v v22.12.0
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/khiettamnguyen/.local/share/fnm/node-versions/v22.12.0/installation/bin/node /Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/lib/binding --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:524:28)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:domain:489:12)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1101:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! node-pre-gyp ERR! System Darwin 24.0.0
npm ERR! node-pre-gyp ERR! command "/Users/khiettamnguyen/.local/share/fnm/node-versions/v22.12.0/installation/bin/node" "/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl
npm ERR! node-pre-gyp ERR! node -v v22.12.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/cache/_logs/2024-12-11T03_24_57_919Z-debug-0.log

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:414:12)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1101:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/bin/npm-cli.js i node-libcurl@4.0.0',
  stdout: '',
  stderr: 'npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.\n' +
    'npm WARN deprecated npmlog@5.0.1: This package is no longer supported.\n' +
    'npm WARN deprecated npmlog@7.0.1: This package is no longer supported.\n' +
    'npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported\n' +
    'npm WARN deprecated are-we-there-yet@4.0.2: This package is no longer supported.\n' +
    'npm WARN deprecated are-we-there-yet@2.0.0: This package is no longer supported.\n' +
    'npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported\n' +
    'npm WARN deprecated gauge@3.0.2: This package is no longer supported.\n' +
    'npm WARN deprecated gauge@5.0.2: This package is no longer supported.\n' +
    'npm ERR! code 1\n' +
    'npm ERR! path /private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl\n' +
    'npm ERR! command failed\n' +
    'npm ERR! command sh -c node-pre-gyp install --fallback-to-build\n' +
    'npm ERR! CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o\n' +
    "npm ERR! Failed to execute '/Users/khiettamnguyen/.local/share/fnm/node-versions/v22.12.0/installation/bin/node /Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/lib/binding --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)\n" +
    'npm ERR! node-pre-gyp info it worked if it ends with ok\n' +
    'npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11\n' +
    'npm ERR! node-pre-gyp info using node@22.12.0 | darwin | arm64\n' +
    'npm ERR! node-pre-gyp info check checked for "/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)\n' +
    'npm ERR! node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v4.0.0/node_libcurl-v4.0.0-node-v127-darwin-arm64-unknown.tar.gz\n' +
    'npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/JCMais/node-libcurl/releases/download/v4.0.0/node_libcurl-v4.0.0-node-v127-darwin-arm64-unknown.tar.gz \n' +
    'npm ERR! node-pre-gyp WARN Pre-built binaries not installable for node-libcurl@4.0.0 and node@22.12.0 (node-v127 ABI, unknown) (falling back to source compile with node-gyp) \n' +
    'npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/JCMais/node-libcurl/releases/download/v4.0.0/node_libcurl-v4.0.0-node-v127-darwin-arm64-unknown.tar.gz \n' +
    'npm ERR! gyp info it worked if it ends with ok\n' +
    'npm ERR! gyp info using node-gyp@10.0.1\n' +
    'npm ERR! gyp info using node@22.12.0 | darwin | arm64\n' +
    'npm ERR! gyp info ok \n' +
    'npm ERR! gyp info it worked if it ends with ok\n' +
    'npm ERR! gyp info using node-gyp@10.0.1\n' +
    'npm ERR! gyp info using node@22.12.0 | darwin | arm64\n' +
    'npm ERR! gyp info find Python using Python version 3.12.6 found at "/Users/khiettamnguyen/.pyenv/versions/3.12.6/bin/python3"\n' +
    'npm ERR! gyp info spawn /Users/khiettamnguyen/.pyenv/versions/3.12.6/bin/python3\n' +
    'npm ERR! gyp info spawn args [\n' +
    "npm ERR! gyp info spawn args '/Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',\n" +
    "npm ERR! gyp info spawn args 'binding.gyp',\n" +
    "npm ERR! gyp info spawn args '-f',\n" +
    "npm ERR! gyp info spawn args 'make',\n" +
    "npm ERR! gyp info spawn args '-I',\n" +
    "npm ERR! gyp info spawn args '/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/build/config.gypi',\n" +
    "npm ERR! gyp info spawn args '-I',\n" +
    "npm ERR! gyp info spawn args '/Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/node_modules/node-gyp/addon.gypi',\n" +
    "npm ERR! gyp info spawn args '-I',\n" +
    "npm ERR! gyp info spawn args '/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/Library/Caches/node-gyp/22.12.0/include/node/common.gypi',\n" +
    "npm ERR! gyp info spawn args '-Dlibrary=shared_library',\n" +
    "npm ERR! gyp info spawn args '-Dvisibility=default',\n" +
    "npm ERR! gyp info spawn args '-Dnode_root_dir=/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/Library/Caches/node-gyp/22.12.0',\n" +
    "npm ERR! gyp info spawn args '-Dnode_gyp_dir=/Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/node_modules/node-gyp',\n" +
    "npm ERR! gyp info spawn args '-Dnode_lib_file=/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/Library/Caches/node-gyp/22.12.0/<(target_arch)/node.lib',\n" +
    "npm ERR! gyp info spawn args '-Dmodule_root_dir=/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl',\n" +
    "npm ERR! gyp info spawn args '-Dnode_engine=v8',\n" +
    "npm ERR! gyp info spawn args '--depth=.',\n" +
    "npm ERR! gyp info spawn args '--no-parallel',\n" +
    "npm ERR! gyp info spawn args '--generator-output',\n" +
    "npm ERR! gyp info spawn args 'build',\n" +
    "npm ERR! gyp info spawn args '-Goutput_dir=.'\n" +
    'npm ERR! gyp info spawn args ]\n' +
    'npm ERR! gyp info ok \n' +
    'npm ERR! gyp info it worked if it ends with ok\n' +
    'npm ERR! gyp info using node-gyp@10.0.1\n' +
    'npm ERR! gyp info using node@22.12.0 | darwin | arm64\n' +
    'npm ERR! gyp info spawn make\n' +
    "npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]\n" +
    "npm ERR! clang++: error: no such file or directory: '/usr/include'\n" +
    'npm ERR! make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 1\n' +
    'npm ERR! gyp ERR! build error \n' +
    'npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2\n' +
    'npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (/Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)\n' +
    'npm ERR! gyp ERR! System Darwin 24.0.0\n' +
    'npm ERR! gyp ERR! command "/Users/khiettamnguyen/.local/share/fnm/node-versions/v22.12.0/installation/bin/node" "/Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/lib/binding" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v127"\n' +
    'npm ERR! gyp ERR! cwd /private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl\n' +
    'npm ERR! gyp ERR! node -v v22.12.0\n' +
    'npm ERR! gyp ERR! node-gyp -v v10.0.1\n' +
    'npm ERR! gyp ERR! not ok \n' +
    'npm ERR! node-pre-gyp ERR! build error \n' +
    "npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/khiettamnguyen/.local/share/fnm/node-versions/v22.12.0/installation/bin/node /Users/khiettamnguyen/nktnet/sample/packagephobia/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl/lib/binding --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)\n" +
    'npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)\n' +
    'npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:524:28)\n' +
    'npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:domain:489:12)\n' +
    'npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1101:16)\n' +
    'npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)\n' +
    'npm ERR! node-pre-gyp ERR! System Darwin 24.0.0\n' +
    'npm ERR! node-pre-gyp ERR! command "/Users/khiettamnguyen/.local/share/fnm/node-versions/v22.12.0/installation/bin/node" "/private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"\n' +
    'npm ERR! node-pre-gyp ERR! cwd /private/var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/tmp-package0.8109899914505192/node_modules/node-libcurl\n' +
    'npm ERR! node-pre-gyp ERR! node -v v22.12.0\n' +
    'npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11\n' +
    'npm ERR! node-pre-gyp ERR! not ok\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in: /var/folders/3w/l9jfq2150ld8sk_0v72mf64c0000gp/T/cache/_logs/2024-12-11T03_24_57_919Z-debug-0.log\n'
}
```

</details>

This seems to be because [node-libcurl](https://github.com/JCMais/node-libcurl) has yet to release binaries for node v22, so it's trying to build the CPP code from source (which wouldn't work on vercel), resulting in the crash.

Perhaps it would be good to show a screen like "Failed to install", or show the logs?

**Comment by styfle** [comment]
Related to https://github.com/JCMais/node-libcurl/issues/421

The reason why I don't print the error message is that its usually not very helpful and in the worse case, exposes internals.
