### ISSUE TITLE
[Just a question] Integrating PackagePhobia API in bestofjs.org

### ISSUE THREAD

**Issue by michaelrambeau** [styfle/packagephobia#120]
Hello, first thank you very much for the great service you provide to the JavaScript community!

I'm running [Best of JavaScript](https://bestofjs.org), an open-source web application that gathers the trends about a curated list of projects on GitHub related to the web platform (JavaScript frontend and backend).

I'd like to include data from _Package Phobia_ API.

Every 24 hours, the application would fetch data for packages that have been updated on NPM over the last 24 hours (usually it means around 50 packages per day, because _Best of JavaScript_ includes about 1000 projects on NPM but not all projects in NPM).

Of course we'd mention that data comes from https://packagephobia.now.sh/ application, providing a link.

It could look like this:

![image](https://user-images.githubusercontent.com/5546996/43997841-e479bf6a-9e21-11e8-83c1-3067614b2ccc.png)

Would it be OK for you?
Do you want us to use a specific header in the HTTP requests we make so that you can easily identify the requests coming from us?

Thank you!

**Comment by styfle** [comment]
Hi Michael, that sounds like a great idea! 😃 

You can use the api or the badge if you would like. And I agree that using a specific User-Agent header would be nice to know that the traffic is coming from your tool.

**Comment by michaelrambeau** [comment]
Hello Steven @styfle 

OK, we are working on the integration (more details [in this issue](https://github.com/bestofjs/bestofjs-webui/issues/61)).

The requests to the API will be made with the following header:

```js
{
  'x-packagephobia-user': 'bestofjs.com'
}
```

FYI during the tests, we noticed some `500 Internal Error`:

* https://packagephobia.now.sh/api.json?p=papercss
* https://packagephobia.now.sh/api.json?p=proton-native
* https://packagephobia.now.sh/api.json?p=node-sass
* https://packagephobia.now.sh/api.json?p=sagui
* https://packagephobia.now.sh/api.json?p=nile.js
* https://packagephobia.now.sh/api.json?p=node-inspector
* https://packagephobia.now.sh/api.json?p=kyt
* https://packagephobia.now.sh/api.json?p=harp
* https://packagephobia.now.sh/api.json?p=semantic-ui
* https://packagephobia.now.sh/api.json?p=angular-seed

Just for fun, the image for errors 500 is pretty good 😄 :

![image](https://user-images.githubusercontent.com/5546996/44006757-b589dde0-9ec4-11e8-8d71-10a2c1e8c67f.png)

So do you know what's wrong with these packages? 

I will tell you as soon as _Best of JavaScript_ update online, thank you for your support!

**Comment by styfle** [comment]
I haven't look at all of them, but most of the time, 500 errors are from `npm install` failing on Alpine Linux.

Often times this is due to native dependencies unable to build.

For example, here's the log from `npm install papercss@1.5.1`:

```
1.1 GET /api.json?p=papercss
Cache miss for papercss@1.5.1 - running npm install in /tmp...
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/tmp-package0.42064753746663097/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/tmp-package0.42064753746663097/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.11.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.11.3',
gyp info spawn args   '-Dnode_gyp_dir=/tmp/tmp-package0.42064753746663097/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.11.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/tmp/tmp-package0.42064753746663097/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /root/.node-gyp/8.11.3
gyp verb 'which' succeeded for 'make' /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
../src/libsass/src/cencode.c: In function 'base64_encode_block':
../src/libsass/src/cencode.c:50:5: warning: empty declaration
     __attribute__ ((fallthrough));
     ^~~~~~~~~~~~~
../src/libsass/src/cencode.c:64:5: warning: empty declaration
     __attribute__ ((fallthrough));
     ^~~~~~~~~~~~~
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: '/usr/app/node_modules/npm/bin/npm-cli.js i --no-package-lock --no-audit papercss@1.5.1',
  stdout: '\n> node-sass@4.9.3 install /tmp/tmp-package0.42064753746663097/node_modules/node-sass\n> node scripts/install.js\n\nCached binary found at /root/.npm/node-sass/4.9.3/linux-x64-57_binding.node\n\n> node-sass@4.9.3 postinstall /tmp/tmp-package0.42064753746663097/node_modules/node-sass\n> node scripts/build.js\n\nBinary found at /tmp/tmp-package0.42064753746663097/node_modules/node-sass/vendor/linux-x64-57/binding.node\nTesting binary\nBinary has a problem: Error: Dynamic loading not supported\n    at Object.Module._extensions..node (module.js:681:18)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)\n    at Module.require (module.js:596:17)\n    at require (internal/module.js:11:18)\n    at module.exports (/tmp/tmp-package0.42064753746663097/node_modules/node-sass/lib/binding.js:19:10)\n    at Object.<anonymous> (/tmp/tmp-package0.42064753746663097/node_modules/node-sass/lib/index.js:14:35)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\nBuilding the binary locally\nBuilding: /usr/bin/node /tmp/tmp-package0.42064753746663097/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=\nmake: Entering directory \'/tmp/tmp-package0.42064753746663097/node_modules/node-sass/build\'\n  g++ \'-DNODE_GYP_MODULE_NAME=libsass\' \'-DUSING_UV_SHARED=1\' \'-DUSING_V8_SHARED=1\' \'-DV8_DEPRECATION_WARNINGS=1\' \'-D_LARGEFILE_SOURCE\' \'-D_FILE_OFFSET_BITS=64\' \'-DLIBSASS_VERSION="3.5.4"\' -I/root/.node-gyp/8.11.3/include/node -I/root/.node-gyp/8.11.3/src -I/root/.node-gyp/8.11.3/deps/openssl/config -I/root/.node-gyp/8.11.3/deps/openssl/openssl/include -I/root/.node-gyp/8.11.3/deps/uv/include -I/root/.node-gyp/8.11.3/deps/zlib -I/root/.node-gyp/8.11.3/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp\n  g++ \'-DNODE_GYP_MODULE_NAME=libsass\' \'-DUSING_UV_SHARED=1\' \'-DUSING_V8_SHARED=1\' \'-DV8_DEPRECATION_WARNINGS=1\' \'-D_LARGEFILE_SOURCE\' \'-D_FILE_OFFSET_BITS=64\' \'-DLIBSASS_VERSION="3.5.4"\' -I/root/.node-gyp/8.11.3/include/node -I/root/.node-gyp/8.11.3/src -I/root/.node-gyp/8.11.3/deps/openssl/config -I/root/.node-gyp/8.11.3/deps/openssl/openssl/include -I/root/.node-gyp/8.11.3/deps/uv/include -I/root/.node-gyp/8.11.3/deps/zlib -I/root/.node-gyp/8.11.3/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast_fwd_decl.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast_fwd_decl.o ../src/libsass/src/ast_fwd_decl.cpp\n  g++ \'-DNODE_GYP_MODULE_NAME=libsass\' \'-DUSING_UV_SHARED=1\' \'-DUSING_V8_SHARED=1\' \'-DV8_DEPRECATION_WARNINGS=1\' \'-D_LARGEFILE_SOURCE\' \'-D_FILE_OFFSET_BITS=64\' \'-DLIBSASS_VERSION="3.5.4"\' -I/root/.node-gyp/8.11.3/include/node -I/root/.node-gyp/8.11.3/src -I/root/.node-gyp/8.11.3/deps/openssl/config -I/root/.node-gyp/8.11.3/deps/openssl/openssl/include -I/root/.node-gyp/8.11.3/deps/uv/include -I/root/.node-gyp/8.11.3/deps/zlib -I/root/.node-gyp/8.11.3/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/backtrace.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/backtrace.o ../src/libsass/src/backtrace.cpp\n  g++ \'-DNODE_GYP_MODULE_NAME=libsass\' \'-DUSING_UV_SHARED=1\' \'-DUSING_V8_SHARED=1\' \'-DV8_DEPRECATION_WARNINGS=1\' \'-D_LARGEFILE_SOURCE\' \'-D_FILE_OFFSET_BITS=64\' \'-DLIBSASS_VERSION="3.5.4"\' -I/root/.node-gyp/8.11.3/include
08/13 11:36 AM (4m)
  stderr: 'npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5\nnpm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js\nnpm WARN deprecated connect@2.30.2: connect 2.x series is deprecated\ngyp info it worked if it ends with ok\ngyp verb cli [ \'/usr/bin/node\',\ngyp verb cli   \'/tmp/tmp-package0.42064753746663097/node_modules/node-gyp/bin/node-gyp.js\',\ngyp verb cli   \'rebuild\',\ngyp verb cli   \'--verbose\',\ngyp verb cli   \'--libsass_ext=\',\ngyp verb cli   \'--libsass_cflags=\',\ngyp verb cli   \'--libsass_ldflags=\',\ngyp verb cli   \'--libsass_library=\' ]\ngyp info using node-gyp@3.8.0\ngyp info using node@8.11.3 | linux | x64\ngyp verb command rebuild []\ngyp verb command clean []\ngyp verb clean removing "build" directory\ngyp verb command configure []\ngyp verb check python checking for Python executable "python2" in the PATH\ngyp verb `which` succeeded python2 /usr/bin/python2\ngyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.14\ngyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j\ngyp verb get node dir no --target version specified, falling back to host node version: 8.11.3\ngyp verb command install [ \'8.11.3\' ]\ngyp verb install input version string "8.11.3"\ngyp verb install installing version: 8.11.3\ngyp verb install --ensure was passed, so won\'t reinstall if already installed\ngyp verb install version is already installed, need to check "installVersion"\ngyp verb got "installVersion" 9\ngyp verb needs "installVersion" 9\ngyp verb install version is good\ngyp verb get node dir target node version installed: 8.11.3\ngyp verb build dir attempting to create "build" dir: /tmp/tmp-package0.42064753746663097/node_modules/node-sass/build\ngyp verb build dir "build" dir needed to be created? /tmp/tmp-package0.42064753746663097/node_modules/node-sass/build\ngyp verb build/config.gypi creating config file\ngyp verb build/config.gypi writing out config file: /tmp/tmp-package0.42064753746663097/node_modules/node-sass/build/config.gypi\ngyp verb config.gypi checking for gypi file: /tmp/tmp-package0.42064753746663097/node_modules/node-sass/config.gypi\ngyp verb common.gypi checking for gypi file: /tmp/tmp-package0.42064753746663097/node_modules/node-sass/common.gypi\ngyp verb gyp gyp format was not specified; forcing "make"\ngyp info spawn /usr/bin/python2\ngyp info spawn args [ \'/tmp/tmp-package0.42064753746663097/node_modules/node-gyp/gyp/gyp_main.py\',\ngyp info spawn args   \'binding.gyp\',\ngyp info spawn args   \'-f\',\ngyp info spawn args   \'make\',\ngyp info spawn args   \'-I\',\ngyp info spawn args   \'/tmp/tmp-package0.42064753746663097/node_modules/node-sass/build/config.gypi\',\ngyp info spawn args   \'-I\',\ngyp info spawn args   \'/tmp/tmp-package0.42064753746663097/node_modules/node-gyp/addon.gypi\',\ngyp info spawn args   \'-I\',\ngyp info spawn args   \'/root/.node-gyp/8.11.3/include/node/common.gypi\',\ngyp info spawn args   \'-Dlibrary=shared_library\',\ngyp info spawn args   \'-Dvisibility=default\',\ngyp info spawn args   \'-Dnode_root_dir=/root/.node-gyp/8.11.3\',\ngyp info spawn args   \'-Dnode_gyp_dir=/tmp/tmp-package0.42064753746663097/node_modules/node-gyp\',\ngyp info spawn args   \'-Dnode_lib_file=/root/.node-gyp/8.11.3/<(target_arch)/node.lib\',\ngyp info spawn args   \'-Dmodule_root_dir=/tmp/tmp-package0.42064753746663097/node_modules/node-sass\',\ngyp info spawn args   \'-Dnode_engine=v8\',\ngyp info spawn args   \'--depth=.\',\ngyp info spawn args   \'--no-parallel\',\ngyp info spawn args   \'--generator-
```

**Comment by michaelrambeau** [comment]
Hello Steven, thank you for your answer.

OK, for now, to avoid performing slow requests that always generate errors, we will track the errors by myself among my data.

Maybe in the future _Package Phobia_ could somehow "catch" those errors and return a JSON `error` object when  the API is called (see below what _Bundle Phobia_ returns for `sagui` package), rather than the 500 error, but it's not a big deal, it's fine for now, don't worry!

```json
{
  "error": {
    "code": "InstallError",
    "message": "Installing the packaged failed.",
  }
}
```

Those packages will be marked as: "No package size data available".

We are getting closer to the next release of _Best of JavaScript_, stay tuned... 😄

**Comment by michaelrambeau** [comment]
Hello Steven @styfle 

Just to confirm, the latest release of https://bestofjs.org/ integrates _Package Phobia_ data, as you can see here.

![image](https://user-images.githubusercontent.com/5546996/44366109-a3b90a80-a506-11e8-937e-65386be67c3c.png)


Thank you for your support!

**Comment by styfle** [comment]
That looks really good! Thanks! 🎉

**Comment by styfle** [comment]
It looks the links don't work for "View details on Package Phobia"

```
https://packagephobia.now.sh/result?p=[object%20Object]
```

Example: https://bestofjs.org/projects/ant-design

**Comment by michaelrambeau** [comment]
Hello @styfle ,
All apologies for the broken links.
The fix has just been released, you may have to reload the page.

Thank you very much for the feedback, I feel so shameful!
And thank you for the tweet too, it's very nice from you!

**Comment by styfle** [comment]
@michaelrambeau Nothing to be ashamed about, everyone makes mistakes! 😄 

You might want to try using TypeScript which could help avoid these types of bugs 👍
