### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by har2008preet** [styfle/packagephobia#484]
Internal Server Error while searching for `realm`. https://packagephobia.now.sh/result?p=realm

**Comment by styfle** [comment]
It fails to install because `realm` requires node-gyp to build and there is no python available at runtime.

```
gyp ERR! stack     at PythonFinder.fail (/var/task/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/var/task/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/var/task/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/var/task/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:314:5)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Linux 4.14.138-99.102.amzn2.x86_64
gyp ERR! command "/var/lang/bin/node" "/var/task/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/tmp/tmp-package0.07823414188284228/node_modules/realm/compiled/node-v72_linux_x64/realm.node" "--module_name=realm" "--module_path=/tmp/tmp-package0.07823414188284228/node_modules/realm/compiled/node-v72_linux_x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
```

**Comment by styfle** [comment]
I don't plan on fixing this. Its not just python but actually building native from source is slow and could time out before it completes. And the size would be different on each platform (Linux, Windows, macOS, etc).
