### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by cherryblossom000** [styfle/packagephobia#597]
The package [@discordjs/opus](https://www.npmjs.com/package/@discordjs/opus) causes a 500 internal server error.

Package Phobia URL: https://packagephobia.com/result?p=%40discordjs%2Fopus
Console:
```
Uncaught TypeError: Cannot set property 'onchange' of null
    at result?p=%40discordjs%2Fopus:103
(anonymous) @ result?p=%40discordjs%2Fopus:103
```
![console](https://user-images.githubusercontent.com/31467609/86894488-79968300-c146-11ea-906b-42d808041071.png)

I couldn't reproduce this for any other packages I tried.

**Comment by styfle** [comment]
The error is happening because python is not installed which is required for node-gyp to build native dependencies.

```
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/var/task/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/var/task/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/var/task/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/var/task/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Linux 4.14.165-102.205.amzn2.x86_64
gyp ERR! command "/var/lang/bin/node" "/var/task/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/tmp/tmp-package0.12310567654316706/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.26/opus.node" "--module_name=opus" "--module_path=/tmp/tmp-package0.12310567654316706/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.26" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /tmp/tmp-package0.12310567654316706/node_modules/@discordjs/opus
```

I don't plan to add python at this time.
