### ISSUE TITLE
500 Internal Server Error when looking for a package

### ISSUE THREAD

**Issue by Psycokwet** [styfle/packagephobia#660]
Hello !

When I try to use package phobia for my packages (bassaudio-updated and bassaudio-updated-light) I get an error 500 :/

Since I would like to add badges to my readme, I don't know what I can do to solve that :o

**Comment by styfle** [comment]
Package Phobia can't handle node-gyp.

Consider providing prebuilt binaries as seen with [sharp](https://packagephobia.com/result?p=sharp).


```
> ref-napi@2.1.2 install /tmp/tmp-package0.0005158906374891359/node_modules/ffi-napi/node_modules/ref-napi
> node-gyp-build
> ref-napi@1.5.2 install /tmp/tmp-package0.0005158906374891359/node_modules/ref-array-napi/node_modules/ref-napi
> node-gyp-build
> ref-napi@1.5.2 install /tmp/tmp-package0.0005158906374891359/node_modules/ref-struct-napi/node_modules/ref-napi
> node-gyp-build
> ffi-napi@3.1.0 install /tmp/tmp-package0.0005158906374891359/node_modules/ffi-napi
> node-gyp-build
events.js:291
      throw er; // Unhandled 'error' event
      ^
Error: spawn node-gyp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}
```
